version: '3'

services:
  devcontainer:
    build: .
    container_name: devcontainer_puzzles
    # command RUNS DIRECTLY WHEN docker compose up
    # .devcontainer/docker-compmose.yaml OVERRIDES it for keep the devcontainer open
    # use it, if you want to execute something when you run `docker compose up` without work with devcontainers
    # command: sh -c '<ANY COMMAND'
    volumes:
      - $HOME/Dev/docker/volumes/go:/home/vscode/go:rw
      - $HOME/Dev/docker/volumes/.m2:/home/vscode/.m2/:rw